<?php
return [
    'GEMINI_API_KEY' => 'AIzaSyDsoaDn2gQPPP-21dxMre3tWl43ZA9YAks',
    'TMDB_API_TOKEN' => 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5MzQ2ZWI2NjY0MGFjMGQ1ZjdiYjY0NzQ2ZWVlZWZlYyIsIm5iZiI6MTc3OTcxODg5Ny42NzIsInN1YiI6IjZhMTQ1YWYxZTVjN2YxNTdiOTU5ZGFlMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.DdZAeN59BQZ1oBnWrBmMEsJuQZhazHAXfhR19oFSclQ',

    'GEMINI_MODEL' => 'gemini-1.5-flash',
];